personal_info = {
    "_notes": [],
    "What_is_your_gender": "",
    "Do_you_consent_to_AW_onal_health_and_care": "",
    "_bamboo_dataset_id": "",
    "_tags": [],
    "What_is_the_personal_ID_number": "",
    "_xform_id_string": "",
    "meta/instanceID": "",
    "Are_you_pregnant_or_lready_have_children": "",
    "What_is_your_Post_Zip_Code": "",
    "What_is_your_town": "",
    "What_is_your_Middle_Name": "",
    "_geolocation": [],
    "What_is_your_First_Name": "",
    "_status": "",
    "__version__": "",
    "What_is_your_Last_Name": "",
    "What_is_your_region": "",
    "_validation_status": {},
    "_uuid": "",
    "What_is_your_date_of_birth": "",
    "_submitted_by": "",
    "formhub/uuid": "",
    "Do_you_have_a_person_entity_card_with_you": "",
    "_submission_time": "",
    "_attachments": [],
    "What_is_your_country": "",
    "_id": 0,
    "Organization":"",
    "CAM": ""
}