from schemas.mapping.mappers import kobo_oldcuris_map as kobo_oldcuris_map
from schemas.mapping.mappers import oldcuris_elastic_map as oldcuris_elastic_map

from schemas.mapping.extractors import kobo2oldcuris_extractor as kobo2oldcuris_extractor
from schemas.mapping.extractors import oldcuris2elastic_extractor as oldcuris2elastic_extractor